# Site settings
name: Learning in Microeconometrics
email: Nanjinzeng@qq.com
author: Nanjin Zeng
url: https://nanjinzeng.github.io/
resume_site: https://nanjinzeng.github.io/
github: https://github.com/NanjinZeng
baseurl: ""
description: Working hard with Inori to make this website work. :-) 
meta_description: Learning in Microeconometrics
motto: Learning in Microeconometrics
banner: Microeconometrics

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: NanjinZeng

# Build settings
markdown: kramdown

